### ISSUE TITLE
Provide PR preview with Netlify

### ISSUE THREAD

**Issue by tomkerkhove** [AzugBe/azugbe.github.io#82]
Provide PR preview with Netlify to make sure that the pages are rendered correctly and can be deployed without noticing it on azug.be.

I can take this up if you want, if you install the "Netlify" GitHub app.

Example: https://github.com/tomkerkhove/promitor/pull/766

**Comment by maartenba** [comment]
Got the app URL? I see netlify logs but not sure that is it?

**Comment by tomkerkhove** [comment]
App Url: https://github.com/apps/netlify

If you go to:
![image](https://user-images.githubusercontent.com/4345663/69549319-5cd38380-0f99-11ea-9305-f3b717ff96bb.png)

It routs you to https://deploy-preview-766--promitor-staging.netlify.com/

And I've added a nice preview banner on top:
![image](https://user-images.githubusercontent.com/4345663/69549351-6bba3600-0f99-11ea-8286-ae7040f2d9ad.png)

**Comment by maartenba** [comment]
Ok installed, build does seem to fail :-/

**Comment by tomkerkhove** [comment]
I'll have a look at it tomorrow!

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________

**Comment by tomkerkhove** [comment]
> Ok installed, build does seem to fail :-/

Can you give a link please?

**Comment by maartenba** [comment]
Seems done?

**Comment by tomkerkhove** [comment]
Jup!
